//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class control_asistencia
    {
        public int id_control { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> id_turno { get; set; }
        public Nullable<System.DateTime> hora_entrada { get; set; }
        public Nullable<System.DateTime> hora_salida { get; set; }
        public Nullable<long> id_empl { get; set; }
    
        public virtual empleado empleado { get; set; }
        public virtual turno turno { get; set; }
    }
}
